server:
  port: 9981

spring:
  jpa:
    database: mysql
    show-sql: true
  datasource:
    druid:

      url: jdbc:mysql://localhost:3306/loansms?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
  redis:
    database: 3
    host: localhost
    port: 6379
    password:
    timeout: 10000
    lettuce: #lettuce client (spring boot默认提供) 基于netty
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8   # 连接池中的最大空闲连接 默认 8
        min-idle: 0


#  cache:
#    cache-names: c1